/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_atware_ac2021_jni_lib_NativeApi */

#ifndef _Included_jp_co_atware_ac2021_jni_lib_NativeApi
#define _Included_jp_co_atware_ac2021_jni_lib_NativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_atware_ac2021_jni_lib_NativeApi
 * Method:    calcByArray
 * Signature: ([[J)J
 */
JNIEXPORT jlong JNICALL Java_jp_co_atware_ac2021_jni_lib_NativeApi_calcByArray
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     jp_co_atware_ac2021_jni_lib_NativeApi
 * Method:    calcByStream
 * Signature: (Ljp/co/atware/ac2021/jni/lib/StreamIterator;)J
 */
JNIEXPORT jlong JNICALL Java_jp_co_atware_ac2021_jni_lib_NativeApi_calcByStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_co_atware_ac2021_jni_lib_NativeApi
 * Method:    calcByStreamChunk
 * Signature: (Ljp/co/atware/ac2021/jni/lib/StreamIterator;)J
 */
JNIEXPORT jlong JNICALL Java_jp_co_atware_ac2021_jni_lib_NativeApi_calcByStreamChunk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
